[package]
name = "parser"
version = "0.1.0"
authors = ["vera"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "1.0.0"
defaults = {path = "../defaults"}
definitions = {path = "../definitions"}
frame-metadata = { version = "15.0.0", default-features = false, features = ["v14", "legacy"]}
hex = "0.4.3"
lazy_static = "1.4.0"
num-bigint = "0.4.3"
parity-scale-codec = {version = "3.0.0", features = ["derive"]}
parity-scale-codec-derive = "3.0.0"
printing_balance = {path = "../printing_balance"}
regex = "1.5.4"
scale-info = "2.0.1"
sp-arithmetic = "4.0.0"
sp-core = {version = "5.0.0", default-features = false, features = ["full_crypto"]}
sp-runtime = "5.0.0"


[lib]
name = "parser"
crate-type = ["lib"]
