[package]
name = "generate_message"
version = "0.1.0"
authors = ["vera"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
constants = {path = "../constants"}
db_handling = {path = "../db_handling"}
definitions = {path = "../definitions"}
hex = "0.4.3"
jsonrpsee-types = "0.9.0"
jsonrpsee-ws-client = "0.9.0"
parity-scale-codec = "3.0.0"
qrcode_rtx = {path = "../qrcode_rtx"}
serde_json = "1.0.64"
sled = "0.34.6"
sp-core = {version = "5.0.0", default-features = false, features = ["full_crypto"]}
tokio = { version = "1", features = ["full"] }
#wasm-loader = "0.13.0"
#wasm-testbed = "0.13.1"
